name: Build TA-Box wheels

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-13, macos-14]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.0.0
        env:
          CIBW_BEFORE_BUILD: >
            pip install -r requirements.txt
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-* cp313-*"
          CIBW_SKIP: "pp* *-musllinux*"
          CIBW_ARCHS: "auto"
          CIBW_TEST_COMMAND: "python -m pytest {project}/tests"
          CIBW_TEST_REQUIRES: "pytest"
          CIBW_BUILD_VERBOSITY: 1

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
